server:
  port: 5555
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/market_fp_db?serverTimezone=GMT
    username: ${DB_USR}
    password: ${DB_PWD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: marcet-service

logging:
  file: logs/log_file.log

